version: '3'

services:

  customer.api:
    image: customer.api       
    build:
      context: ./services/customer.api
      dockerfile: Dockerfile.debug
    ports: 
    - "8081:80"
    container_name: customer.api

  pet.api:
    image: pet.api
    build:
      context: ./services/pet.api
      dockerfile: Dockerfile.debug
    ports: 
    - "8084:80"
    container_name: pet.api    
    
  frontend:
    image: frontend.cangos
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    container_name: frontend.cangos

