version: '3'

services:

  customer.api:
    image: customer.api       
    build:
      context: ./services/customer.api
      dockerfile: Dockerfile.debug
    ports: 
    - "8081:80"
    container_name: customer.api
    networks:
    - "cangos"

  pet.api:
    image: pet.api
    build:
      context: ./services/pet.api
      dockerfile: Dockerfile.debug
    ports: 
    - "8084:80"
    container_name: pet.api    
    networks:
    - "cangos"
    
  frontend:
    image: frontend.cangos
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    container_name: frontend.cangos
    volumes:
      - "./frontend:/cangos"
    networks:
    - "cangos"

  elasticsearch:
    container_name: elasticsearch.cangos
    image: elasticsearch
    ports:
      - "9200:9200"
    networks:
      - "cangos"

networks: 
    cangos:
